parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_DEFAULT_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            stat:
                url: '%env(resolve:DATABASE_STAT_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            service:
                url: '%env(resolve:DATABASE_SERVICE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            stat:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: stat
                mappings:
                    Stat:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Stat'
                        prefix: 'App\Entity\Stat'
                        alias: Stat
            service:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: service
                mappings:
                    Service:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Service'
                        prefix: 'App\Entity\Service'
                        alias: Service
