showTodos:
  path: /todo
  controller: App\Controller\TodosController::getTodos

completeTodo:
  path: /todo/{id}
  controller: App\Controller\TodosController::tryChangeTodo
  methods: PATCH
  requirements:
    id: '[1-9][0-9]*'
