migrations_directory: 'src/Migrations/Stat'

# namespace is arbitrary but should be different from App\Migrations
# as migrations classes should NOT be autoloaded
migrations_namespace: DoctrineMigrations\Stat
